### PR TITLE
add Redis authentication

### PR DESCRIPTION
**Pull request by erm156**
- using authentication with `JedisPool` and `JedisCluster` requires additional parameters in the constructor (I used placeholder values and can update them and/or add them to the config if needed):
```java
JedisCluster(HostAndPort node, int connectionTimeout, int soTimeout, int maxAttempts, String password, org.apache.commons.pool2.impl.GenericObjectPoolConfig poolConfig)

JedisPool(org.apache.commons.pool2.impl.GenericObjectPoolConfig poolConfig, String host, int port, int timeout, String password)
```

### CODE REVIEW

**Review by n2iw — CHANGES_REQUESTED** [review]
Code looks good, but please rebase the code change to ICDC-development, and change PR to merge back to that branch, thanks!

**Comment by erm156** [comment]
Rebased `ICDC-3076` branch onto `ICDC-development` and updated PR base branch.

**Review by n2iw — CHANGES_REQUESTED** [review]
Please check if the code related to "extra-filters" is needed, if not, please remove it.

**Comment by erm156** [comment]
Reverted the extraneous commits (one was the filters added by Young, the other was a newline that I think my auto-formatter added)

**Review by n2iw — APPROVED** [review]
LGTM

**Pull request merged**
